## this compose is for developing wish itself.
## for your own project app, read the docs

version: '2.4'

services:

  wish:
    container_name: websh
    stop_signal: "9"
    image: websh
    build:
      context: .
    volumes:
      - $PWD:/www
      - ./example-app:/www/app
    ports:
      - "80:80"
      - "5000:5000"
